#!/bin/bash

[ -z "$2" ] && echo "Run dt-install-sandbox-software to call this script" && exit 1

# This script is called via the dt-install-sandbox-software command.
# Do not run it directly.  Further, this is called prior to the
# sandbox environment being loaded into the shell so any variables
# needed from the defaults.sh (or other env file) must be setup
# manually.

export GORE_SANDBOX=$1  # root of the sandbox
export GORE_TOP=$2      # root of the primary git project
SB_ENV_FILE=$3            # name of the environment file to use
export GORE_NAME=`dirname $GORE_SANDBOX`
[ -z "$SB_ENV_FILE" ] && SB_ENV_FILE=defaults.sh


. $GORE_TOP/sandbox/$SB_ENV_FILE

# Install node if specified with GORE_NODE_VER
[ -n "$GORE_NODE_VER" -a ! -L $GORE_SANDBOX/node ] && dt-get-software -V $GORE_NODE_VER node $GORE_SANDBOX

# Install yarn if specified with GORE_YARN_VER
[ -n "$GORE_YARN_VER" -a ! -L $GORE_SANDBOX/yarn ] && dt-get-software -V $GORE_YARN_VER yarn $GORE_SANDBOX



# Put custom one-time only software installations here (such as git clones of additional repos,
# other software packages that will live in the sandbox, etc...).
#
# Note that there is no sandbox process, other than a first time install, that exeutes this hook.


exit 0
